### ISSUE TITLE
Wrong template processing with proxy hostname

### ISSUE THREAD

**Issue by trayla** [xetus-oss/helm-charts#5]
It want to deploy the Helm chart with a proxy setting like this:
```
proxy:
    enabled: true
    hostname: abc.example.com
```
This cannot be parsed into a Kubernetes ressource because it generates a result like this:
```
...
          env:
            - name: SMTP_HOST
              value:
            - name: SMTP_PORT
              value: "25"
            - name: PROXY_BASE_URL
              value:
  https://abc.example.com
            - name: JVM_MAX_MEM
              value: "768"
...
```
Obviously there is a leading line feed inserted which is not from my values file. Does anybody know, how to fix this?
